In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

DATA_PATH = '../../../data/processed'

In [ ]:
# Bases processadas por fase, participante e condição
df_eda_p1 = pd.read_csv(f'{DATA_PATH}/eda_normalizado_p1v4.csv')
df_eda_p2 = pd.read_csv(f'{DATA_PATH}/eda_normalizado_p2v4.csv')

# Bases processadas por fase e janelas de 40s
df_pi2905_sawyer = pd.read_excel(f'{DATA_PATH}/PI-2905/40s_overlap50_Sawyer_agg_order.xlsx')
df_pi2905_ur10 = pd.read_excel(f'{DATA_PATH}/PI-2905/40s_overlap50_UR10_agg_order.xlsx')

In [26]:
df_eda_p1.shape

(131, 47)

In [27]:
df_pi2905_sawyer.shape

(142, 40)

In [19]:
df_eda_p1['Subject'] = df_eda_p1['participant'].apply(lambda p: int(p[-2:]))
df_eda_p1 = df_eda_p1.rename({'condition': 'Condition'}, axis=1)
df_eda_p1[['participant', 'Subject']]

    participant  Subject
0           S06        6
1           S06        6
2           S06        6
3           S06        6
4           S06        6
..          ...      ...
126         S30       30
127         S30       30
128         S30       30
129         S30       30
130         S30       30

[131 rows x 2 columns]

In [28]:
df_p1 = pd.merge(left = df_eda_p1[['Subject', 'Condition', 'errors']], right = df_pi2905_sawyer, how="right", on=["Subject", "Condition"])
df_p1['origin'] = 'sawyer'
df_p1

,Subject,Condition,errors,Code,Speed,Proximity,Order,HR_BPM,RMSSD,SDNN,...,EDA_SM_Phasic_Mean,EDA_SM_Phasic_AUC,EDA_SM_Phasic_nPeaks,EDA_SM_SCR_RiseTime,EDA_SM_SCR_Amplitude_Mean,Temp_Mean,Temp_Std,Temp_Slope,Start_min,origin
0,6,V3P1,19.0,11,V3,P1,2,82.987497,58.458733,50.941212,...,0.005336,0.213363,19.0,0.559028,0.018879,-0.053254,0.002925,2.517027e-04,3.532873,sawyer
1,6,V2P2,12.0,10,V2,P2,3,82.229231,39.076153,48.381044,...,0.002298,0.091895,7.0,1.024740,0.031179,0.007511,0.001300,1.119182e-04,8.003206,sawyer
2,6,V3P2,19.0,12,V3,P2,4,82.770386,60.234428,66.317346,...,0.003109,0.124347,12.0,0.853232,0.014874,0.019901,0.000705,3.640286e-05,13.794873,sawyer
3,6,V2P1,12.0,9,V2,P1,5,83.852901,73.823440,75.730977,...,0.001642,0.065549,24.5,0.557639,0.005068,0.021971,0.000860,7.343938e-05,18.492206,sawyer
4,6,V1P1,8.0,7,V1,P1,6,84.728307,149.464321,106.856818,...,0.003249,0.129827,20.0,0.607422,0.007371,0.004370,0.001620,-1.401649e-04,23.631206,sawyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,30,V3P1,14.0,11,V3,P1,2,72.680712,231.882478,161.014622,...,0.006542,0.261668,16.0,0.902451,0.012225,-0.002191,0.000274,2.200414e-05,4.452801,sawyer
138,30,V1P2,1.0,8,V1,P2,3,68.626558,108.398855,100.646316,...,0.006624,0.264907,13.0,1.127504,0.017280,0.012762,0.000226,1.855217e-05,8.916135,sawyer
139,30,V2P1,8.0,9,V2,P1,4,74.033626,62.402001,80.199223,...,0.005062,0.201972,10.5,1.543490,0.013877,0.013087,0.000537,-2.386228e-05,13.231468,sawyer
140,30,V3P2,4.0,12,V3,P2,5,70.996595,268.064400,169.812638,...,0.006704,0.268168,10.0,1.036458,0.017892,0.013977,0.000420,-3.629553e-05,17.449801,sawyer
141,30,V1P1,0.0,7,V1,P1,6,72.478542,79.135959,95.946313,...,0.004442,0.177682,11.0,1.461806,0.015227,0.005056,0.000533,-6.984160e-07,22.011801,sawyer

In [29]:
df_p1.to_csv('sawyer_errors.csv')

In [30]:
df_eda_p2.shape

(300, 45)

In [31]:
df_pi2905_ur10.shape

(368, 51)

In [36]:
df_eda_p2['Subject'] = df_eda_p2['participant'].apply(lambda p: int(p[-3:]))
df_eda_p2 = df_eda_p2.rename({'condition': 'Condition', 'secondary_task': 'Secondary_task'}, axis=1)
df_eda_p2[['participant', 'Subject']]

    participant  Subject
0          S104      104
1          S104      104
2          S104      104
3          S104      104
4          S104      104
..          ...      ...
295        S134      134
296        S134      134
297        S134      134
298        S134      134
299        S134      134

[300 rows x 2 columns]

In [40]:
df_p2 = pd.merge(left = df_eda_p2[['Subject', 'Condition', 'Secondary_task', 'errors']], right = df_pi2905_ur10, how="right", on=["Subject", "Condition", "Secondary_task"])
df_p2['origin'] = 'ur10'
df_p2

,Subject,Condition,Secondary_task,errors,Code,Speed,Proximity,Order,HR_BPM,RMSSD,...,EDA_SM_Phasic_Mean,EDA_SM_Phasic_AUC,EDA_SM_Phasic_nPeaks,EDA_SM_SCR_RiseTime,EDA_SM_SCR_Amplitude_Mean,Temp_Mean,Temp_Std,Temp_Slope,Start_min,origin
0,101,V1P1,no,NaN,1,V1,P1,1,80.305155,114.318935,...,0.001345,0.053711,7.0,2.252604,0.003332,-0.013020,0.001492,-0.000128,4.342232,ur10
1,101,V3P1,no,NaN,5,V3,P1,2,84.359375,81.721599,...,0.001495,0.059809,6.0,1.732143,0.008907,0.009689,0.000539,-0.000034,10.286089,ur10
2,101,V3P2,no,NaN,6,V3,P2,3,84.694045,88.664331,...,0.003125,0.124605,5.0,2.088542,0.013110,0.012910,0.002070,-0.000179,14.527694,ur10
3,101,V1P2,no,NaN,2,V1,P2,4,83.023701,82.511434,...,0.001180,0.047183,4.0,1.781250,0.011534,0.010945,0.000553,0.000016,18.912592,ur10
4,101,V2P2,no,NaN,4,V2,P2,5,88.643882,95.018954,...,0.004096,0.163721,7.0,1.414062,0.014565,0.019465,0.000531,-0.000023,22.964067,ur10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,134,V3P2,no,0.0,6,V3,P2,8,84.700815,41.565758,...,0.000602,0.024091,11.0,0.826705,0.004451,-0.002228,0.000248,-0.000005,26.955951,ur10
364,134,V1P2,no,0.0,2,V1,P2,9,80.644745,55.647239,...,0.001216,0.048625,15.0,1.044997,0.004523,-0.006245,0.000191,0.000002,30.379618,ur10
365,134,V2P2,no,0.0,4,V2,P2,10,80.864246,37.189894,...,0.000348,0.013851,7.0,1.401042,0.001445,-0.011951,0.000502,-0.000043,36.523285,ur10
366,134,V3P1,no,0.0,5,V3,P1,11,83.530294,30.962136,...,0.000455,0.018187,9.0,1.253906,0.002003,-0.013889,0.000670,0.000058,40.318618,ur10
367,134,V1P1,no,0.0,1,V1,P1,12,79.037608,43.056649,...,0.000558,0.022315,12.0,0.659091,0.004258,-0.011904,0.000603,0.000052,43.611951,ur10

In [41]:
df_p2.to_csv('ur10_errors.csv')